export const CART_LIST_REQUEST = "CART_LIST_REQUEST";
export const CART_LIST_SUCCESS = "CART_LIST_SUCCESS";
export const CART_LIST_FAIL = "CART_LIST_FAIL";
export const CART_ITEM_ADD_REQUEST = "CART_ITEM_REQUEST";
export const CART_ITEM_ADD_SUCCESS = "CART_ITEM_SUCCESS";
export const CART_ITEM_ADD_FAIL = "CART_ITEM_FAIL";
